### ISSUE TITLE
Usernames, passwords, session IDs, etc are plainly logged

### ISSUE THREAD

**Issue by jamin-bagel** [iChauster/GradeCheck#1]
On these lines and others, usernames, passwords and valid session ids are plainly logged to the console.

https://github.com/iChauster/GradeCheck/blob/d7d1ecd1a514db88e3be036151a768dba64afda0/routes/index.js#L217-L218

I understand that this was a messy side-project that you probably never want to touch again, but I don't think that anyone would use this app if they knew how easily anyone with console access could access their personal info, and I certainly will not use it until something is done. Most of the logging appears to be for debugging purposes anyways, so deleting most of your console.logs in a single commit should do no harm.

**Comment by iChauster** [comment]
Hey Jamin, 

Any feedback is appreciated, so thanks for the heads-up! This repository has been really overlooked, and honestly difficult to look at given the code quality, but thanks for bringing my attention back to it again! The codebase has grown over the years and so the repository you had looked at didn't actually reflect what was actually in production. You're completely right in that those were for debugging purposes. 

Since I have graduated, I decided it would be a good idea to release the production versions of the code and obscure anything that might give away private information -- including what you noted above.  Hope you can find what you're looking for, and if you have any questions at all, I'd be happy to answer them.
